//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseCrawlerFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class people
    {
        public int person_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public int account_type { get; set; }
        public int dob { get; set; }
        public string compress_pass { get; set; }
        public string hash_pass { get; set; }
        public string enc_pass { get; set; }
    }
}
