//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseCrawlerFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tv
    {
        public int tv_id { get; set; }
        public string tv_title { get; set; }
        public int num_seasons { get; set; }
    }
}
